### ISSUE TITLE
-login required to get a profile's followers.

### ISSUE THREAD

**Issue by dizzy1301** [new92/IGFollowersIncreaser#35]
Traceback (most recent call last):                                           
  File "/home/dizzy/IGFollowersIncreaser/InstagramFollowers/V1/mainV1.py", line 819, in <module>                                                          
    main()                                                                   
  File "/home/dizzy/IGFollowersIncreaser/InstagramFollowers/V1/mainV1.py", line 375, in main                                                              
    FOLLOWERS = [follower.username for follower in profile.get_followers()]  
                                                   ^^^^^^^^^^^^^^^^^^^^^^^   
  File "/usr/local/lib/python3.11/dist-packages/instaloader/structures.py", line 1053, in get_followers                                                   
    raise LoginRequiredException("--login required to get a profile's followers.")                                                                        
instaloader.exceptions.LoginRequiredException: --login required to get a profile's followers.

what should I do? im using Kali

**Comment by new92** [comment]
Hey @dizzy1301, so if you haven't made any changes to the script's code this error shouldn't appear. If you haven't made any changes try deleting it and reinstalling it again. Also please make sure that your credentials are correct.
